### PR TITLE
HuffmanTree_cleanup: change initializer of mask to a real constant constant

### PR DESCRIPTION
**Pull request by sezero**
fixes build by Watcom.

### CODE REVIEW

**Comment by lvandeve** [comment]
Hi, what's the error message that Watcom gives for this? Thanks

**Comment by sezero** [comment]
> Hi, what's the error message that Watcom gives for this? Thanks

`lodepng.c(613): Error! E1054: Expression must be constant`

**Comment by lvandeve** [comment]
Hmm, I wonder why gcc and clang aren't giving this error. Accepting in case it breaks on more compilers, thanks for finding this!

**Comment by sezero** [comment]
> Hmm, I wonder why gcc and clang aren't giving this error.

Watcom is too strict for it.  IIRC, it used to have a special switch that makes
it accecpt non-constant initializers?, but never used it my self and don't know
how experimental/reliable it is.

**Pull request merged**
