### PR TITLE
Small tweaks

### PR DESCRIPTION
**Pull request by zeptoZB**
Removed warnings.
Small tweaks for better 64-bit compatibility.
Small tweaks for build in Visual Studio.

### CODE REVIEW

**Comment by stinos** [comment]
Better split this into commits, 1 for each logical change.  Btw there are already multiple pull requests for the warnings/64-bit compatibility issues. You should probably also explain why you need to tweak the buid for VS: I doubt this would get merged without any explanation of why the changes are needed.

**Comment by zeptoZB** [comment]
The changes are minimal, in my opinion very simple to understand, looking at the changes is easier to understand than a long text explaining the reason for each change ... But that's how I work... There is no right or wrong, what is good for one may be unsatisfactory for another...

**Comment by stinos** [comment]
The changes are indeed very simple to understand, as in: sure it's easy to see *what* has changed. The *why* might be way less obvious though, especially for *other* people. Also because you're burrying behaviour changes like the change in line 1174 in a quite big diff, in a commit named 'small tweaks'. That's quite a long way from just 'unsatisfactory' as far as commit organization/messages go.

**Comment by zeptoZB** [comment]
I closed the request because it has alternate paths (disabling some warnings in Visial Studio) and will only keep the relevant changes ...

**Pull request closed without merging**
